plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ziptool.uploader'
    compileSdk 34

    defaultConfig {
        applicationId "com.ziptool.uploader"
        minSdk 21
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig = false
    }
}
